### ISSUE TITLE
How to add page numbers in a citation

### ISSUE THREAD

**Issue by ge** [evolve2k/obsidian-pandoc-academic-word-doc-guide#4]
Your workflow step [How to add page numbers in a citation](https://github.com/evolve2k/obsidian-pandoc-academic-word-doc-guide#how-to-add-page-numbers-in-a-citation) doesn't say what you're adding the citation **to**!?  I'm guessing to Zotero, but the keystrokes you suggest doesn't do anything to my Zotero docs.

Also, I assume at some point, you import your Zotero notes (?) into Obsidian, but I don't see that in the workflow.

Is Pandoc invoked from the command-line, from inside Obsidian?  

Sorry to be so clueless.  I was excited to see this document, but I need carefully-described instructions.

**Comment by evolve2k** [comment]
Thanks for your questions, sorry I must have missed this earlier.

The workflow is as follows.
1. All your academic papers are saved into Zotero along with references to books, websites etc.
2. Zotero is synced to Obsidian, which lets you write papers and notes in Obsidian and add references to sources from Zotero.
3. So now you want to convert one of your Obsidian notes into an "academic paper". The tool you need for this is pandoc. The pandoc tool understands many academic referencing styles such as APA7 and Harvard. Specifically you install the pandoc plugin for Obsidian and configure that.
4. Once the pandoc plugin is setup; On the note you want to convert to an 'academic paper' you can run the pandoc command and it will generate a Word Document that automatically includes correct inline referencing and an auto-generated references section with all the references listed, at the end of the document.

In this way for academics papers you are drafting yourself, you can keep all your references in Zotero, write efficiently in Obsidian and easily look up the zotero references, and then when it's time.. generate an academic paper with a fast keyboard shortcut.

Let me know if you have more questions, or if you'd like me to record a video of this workflow.
